import Head from "next/head";
import Navbar from "~/components/navbar";
import Footer from "~/components/footer";
// import Link from "next/link";
// import Image from "next/image";



export default function Edit() {

  return (
    <>
      <Head>
        <title>Scan your text</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" flex min-h-screen flex-col bg-dark">
        <Navbar/>
        <h1 className="text-white mt-6 ml-10 mb-4">
                Get started with Source Scanner. 
        </h1>
        <div className="flex mx-10 gap-8">
            <div className="flex flex-col w-1/2">
                <form className="">
                    <textarea className="w-full h-[60vh] resize-none bg-secondary text-white rounded-lg p-6 focus-visible:border-white border-2 focus-within:border-white" placeholder="Enter your text here"></textarea>
                </form>

                <div className="flex justify-end">
                    <button className="bg-primary text-white rounded-lg p-4 mt-2 ">Scan</button>
                </div>
            </div>

            <div className=" w-1/2 pt-6 bg-white h-[60vh] rounded-lg px-10">
                <p className="overflow-auto">text</p>
            </div>
        </div>
        <Footer/>
      </main>
    </>
  );
}
