import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Navbar from "~/components/navbar";
import Footer from "~/components/footer";
import Image from "next/image";
import { Tooltip, Button } from 'flowbite-react'



import { api } from "~/utils/api";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col  bg-dark">
        <Navbar />
        <section className="flex flex-col flex-1 px-20">
          <h1 className="text-6xl font-bold text-white mt-20 text-center">
            scan your text,<br /> <span className="text-primary underline decoration-dashed">understand</span> the words.
          </h1>
          <div className="flex gap-6">
            <div className="bg-secondary w-1/2 mt-10 rounded-md border-2 border-white">
              <p className="p-4 text-white">
                A hackathon is a great way to learn about ways you can manipulate code and software in unique and interesting ways.</p>
            </div>
            <div className="bg-[#f5f5f5] w-1/2 mt-10 rounded-md">
              <div className="p-4 text-dark gap-2 inline-block">
                A 
                <Tooltip content="pst">
                  <span className="text-primary transition duration-150 ease-in hover:text-primary focus:text-primary active:text-primary_dark underline decoration-dashed"> hackathon </span>
                </Tooltip> 
                is a great way to learn about ways you can manipulate code and software in unique and interesting ways.
              </div>
            </div>
          </div>
        </section>
        <Footer/>
      </main>
    </>
  );
}
